image: php:7.2-alpine

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

before_script:
  - 'docker-php-ext-install pdo pdo_mysql'
  - 'echo "Setting up TEST environment variables"'
  - '[ -e .env ] && rm .env'
  - 'touch .env'
  - 'echo "APP_ENV=$APP_ENV" >> .env'
  - 'echo "APP_DEBUG=$APP_DEBUG" >> .env'
  - 'echo "APP_KEY=$APP_KEY" >> .env'
  - 'echo "APP_TIMEZONE=$APP_TIMEZONE" >> .env'
  - 'echo "DB_CONNECTION=$DB_CONNECTION" >> .env'
  - 'echo "DB_HOST=$TEST_DB_HOST" >> .env'
  - 'echo "DB_PORT=$DB_PORT" >> .env'
  - 'echo "DB_DATABASE=$DB_DATABASE" >> .env'
  - 'echo "DB_USERNAME=$DB_USERNAME" >> .env'
  - 'echo "DB_PASSWORD=$DB_PASSWORD" >> .env'
  - 'echo "LOG_CHANNEL=$LOG_CHANNEL" >> .env'
  - 'echo "CACHE_DRIVER=$CACHE_DRIVER" >> .env'
  - 'echo "QUEUE_DRIVER=$QUEUE_DRIVER" >> .env'
  - 'echo "ACCESS_TOKEN_AGE=$ACCESS_TOKEN_AGE" >> .env'
  - 'cat .env'

build_run_composer_install:
  stage: build
  image: composer
  before_script:
    - 'composer -v'
  script:
    - 'composer install'
  after_script:
    - 'composer dump-autoload'

test_run_unit_tests:
  stage: test
  before_script:
    - 'cat .env'
  script:
    - 'php artisan migrate:fresh --seed'
    - 'vendor/bin/phpunit'
