stages:
  - build
  - test

build_run_composer_install:
  stage: build
  image: composer
  before_script:
    - composer -v
  script:
    - composer install
  after_script:
    - composer dump-autoload

test_run_unit_tests:
  stage: test
  image: php7.2
  before_script:
    - php -v
  script:
    - vendor/bin/phpunit
