image: php:7.2-alpine

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

build_run_composer_install:
  stage: build
  image: composer
  before_script:
    - 'composer -v'
  script:
    - 'composer install'
  after_script:
    - 'composer dump-autoload'

test_run_unit_tests:
  stage: test
  before_script:
    - 'docker-php-ext-install pdo pdo_mysql'
    - 'echo "Setting up TEST environment variables"'
    - '[ -e .env ] && rm .env'
    - 'touch .env'
    - 'echo "APP_ENV=$TEST_APP_ENV" >> .env'
    - 'echo "APP_DEBUG=$TEST_APP_DEBUG" >> .env'
    - 'echo "APP_KEY=$TEST_APP_KEY" >> .env'
    - 'echo "APP_TIMEZONE=$TEST_APP_TIMEZONE" >> .env'
    - 'echo "DB_CONNECTION=$TEST_DB_CONNECTION" >> .env'
    - 'echo "DB_HOST=$TEST_DB_HOST" >> .env'
    - 'echo "DB_PORT=$TEST_DB_PORT" >> .env'
    - 'echo "DB_DATABASE=$TEST_DB_DATABASE" >> .env'
    - 'echo "DB_USERNAME=$TEST_DB_USERNAME" >> .env'
    - 'echo "DB_PASSWORD=$TEST_DB_PASSWORD" >> .env'
    - 'echo "LOG_CHANNEL=$TEST_LOG_CHANNEL" >> .env'
    - 'echo "CACHE_DRIVER=$TEST_CACHE_DRIVER" >> .env'
    - 'echo "QUEUE_DRIVER=$TEST_QUEUE_DRIVER" >> .env'
    - 'echo "ACCESS_TOKEN_AGE=$TEST_ACCESS_TOKEN_AGE" >> .env'
    - 'cat .env'
  script:
    - 'php artisan migrate:fresh --seed'
    - 'vendor/bin/phpunit'
