image: php:7.2-alpine

stages:
  - build
  - test

build_run_composer_install:
  stage: build
  image: composer
  before_script:
    - composer -v
  script:
    - composer install
  after_script:
    - composer dump-autoload

test_setup_env:
  stage: test
  before_script:
    - echo "Printing all variables:"
    - echo $APP_ENV
