stages:
  - preparation
  - test
  - build
  - deploy

variables:
  CONTAINER_REGISTRY: registry.gitlab.com/dewadg/synchrome-api
  CONTAINER_NAME: synchrome-api

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

composer_install:
  stage: preparation
  image: composer
  only:
    - master
  script:
    - composer install

unit_test:
  stage: test
  image: php:7.2-alpine
  only:
    - master
  variables:
    APP_ENV: $TEST_APP_ENV
    APP_DEBUG: $TEST_APP_DEBUG
    APP_KEY: $TEST_APP_KEY
    APP_TIMEZONE: $TEST_APP_TIMEZONE
    DB_CONNECTION: $TEST_DB_CONNECTION
    DB_HOST: $TEST_DB_HOST
    DB_DATABASE: $TEST_DB_DATABASE
    DB_USERNAME: $TEST_DB_USERNAME
    DB_PASSWORD: $TEST_DB_PASSWORD
    LOG_CHANNEL: $TEST_LOG_CHANNEL
    CACHE_DRIVER: $TEST_CACHE_DRIVER
    QUEUE_DRIVER: $TEST_QUEUE_DRIVER
    ACCESS_TOKEN_AGE: $TEST_ACCESS_TOKEN_AGE
  before_script:
    - docker-php-ext-install pdo pdo_mysql
  script:
    - vendor/bin/phpunit

build:
  stage: build
  image: docker
  only:
    - master
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build . -t $CONTAINER_REGISTRY:latest
  after_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $CONTAINER_REGISTRY:latest

deploy:
  stage: deploy
  image: ubuntu:latest
  only:
    - master
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$PROD_SERVER_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $PROD_SERVER_ADDRESS >> ~/.ssh/known_hosts
  script:
    - |
      ssh $PROD_SERVER_USER@$PROD_SERVER_ADDRESS "
        docker rm -f $CONTAINER_NAME 2> /dev/null;
        docker pull $CONTAINER_REGISTRY:latest;
        docker create --name $CONTAINER_NAME \
          --network synchrome_net \
          -p 8000:80 \
          -e APP_ENV=$PROD_APP_ENV \
          -e APP_DEBUG=$PROD_APP_DEBUG \
          -e APP_KEY=$PROD_APP_KEY \
          -e APP_TIMEZONE=$PROD_APP_TIMEZONE \
          -e DB_CONNECTION=$PROD_DB_CONNECTION \
          -e DB_HOST=$PROD_DB_HOST \
          -e DB_DATABASE=$PROD_DB_DATABASE \
          -e DB_USERNAME=$PROD_DB_USERNAME \
          -e DB_PASSWORD=$PROD_DB_PASSWORD \
          -e LOG_CHANNEL=$PROD_LOG_CHANNEL \
          -e CACHE_DRIVER=$PROD_CACHE_DRIVER \
          -e QUEUE_DRIVER=$PROD_QUEUE_DRIVER \
          -e ACCESS_TOKEN_AGE=$PROD_ACCESS_TOKEN_AGE \
          $CONTAINER_REGISTRY;
        docker start $CONTAINER_NAME;
        docker exec -d $CONTAINER_NAME php artisan migrate:seed;
        exit;
      "
