image: php:7.2

stages:
  - build

build_run_composer_install:
  stage: build
  before_script:
    - apt update
    - apt upgrade -y
    - apt install composer -y
    - composer -v
  script:
    - composer install
  after_script:
    - composer dump-autoload
