stages:
  - preparation
  - test
  - deploy

variables:
  IMAGE_REGISTRY: registry.gitlab.com/dewadg/synchrome-api
  CONTAINER_NAME: synchrome-api

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

run_composer_install:
  stage: preparation
  image: composer
  before_script:
    - composer -v
  script:
    - composer install
  after_script:
    - composer dump-autoload

run_unit_tests:
  stage: test
  image: php:7.2-alpine
  variables:
    APP_ENV: $TEST_APP_ENV
    APP_DEBUG: $TEST_APP_DEBUG
    APP_KEY: $TEST_APP_KEY
    APP_TIMEZONE: $TEST_APP_TIMEZONE
    DB_CONNECTION: $TEST_DB_CONNECTION
    DB_HOST: $TEST_DB_HOST
    DB_DATABASE: $TEST_DB_DATABASE
    DB_USERNAME: $TEST_DB_USERNAME
    DB_PASSWORD: $TEST_DB_PASSWORD
    LOG_CHANNEL: $TEST_LOG_CHANNEL
    CACHE_DRIVER: $TEST_CACHE_DRIVER
    QUEUE_DRIVER: $TEST_QUEUE_DRIVER
    ACCESS_TOKEN_AGE: $TEST_ACCESS_TOKEN_AGE
  before_script:
    - docker-php-ext-install pdo pdo_mysql
  script:
    - php artisan migrate:fresh --seed
    - vendor/bin/phpunit

generate_image:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker version
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_REGISTRY:latest .
    - docker push $IMAGE_REGISTRY:latest

deploy:
  stage: deploy
  image: ubuntu
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$PROD_SERVER_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh $PROD_SERVER_USER@$PROD_SERVER_ADDRESS
    - docker pull $IMAGE_REGISTRY:latest
    - docker rm -f $CONTAINER_NAME
    - docker create --name $CONTAINER_NAME -p 8000:80 $IMAGE_REGISTRY
    - docker run $CONTAINER_NAME
